language: c

before_install:
  - sudo apt-get install gnat

jobs:
  include:
    - stage: gnu-make
      script: cd $TRAVIS_BUILD_DIR/gnu-make-hello && make && ./hello
    - stage: gnatmake
      script: cd $TRAVIS_BUILD_DIR/gnatmake-hello && gnatmake hello.adb && ./hello
