language: c

before_install:
  - sudo apt-get install gnat

jobs:
  include:
    - stage: dummy
      script: g++ --print-libgcc-file-name && ls -la /usr/lib/gcc/x86_64-linux-gnu/4.8/adalib/libgnat.a

#    - stage: gnu-make
#      script: cd $TRAVIS_BUILD_DIR/gnu-make-hello && make && ./hello
#    - stage: gnatmake
#      script: cd $TRAVIS_BUILD_DIR/gnatmake-hello && make && ./hello
#    - stage: ada-main-c-depend
#      script: cd $TRAVIS_BUILD_DIR/ada-main-c-depend && make && ./main
#    - stage: c-main-ada-depend
#      script: cd $TRAVIS_BUILD_DIR/c-main-ada-depend && make && ./main
#    - stage: ada-main-cpp-depend
#      script: cd $TRAVIS_BUILD_DIR/ada-main-cpp-depend && make && ./main
#    - stage: cpp-main-ada-depend
#      script: cd $TRAVIS_BUILD_DIR/cpp-main-ada-depend && make && ./main
#    - stage: ada-main-big
#      script: cd $TRAVIS_BUILD_DIR/ada-main-big && make && ./bin/main
