language: c

before_install:
  - sudo apt-get install gnat

jobs:
  include:
    - stage: gnu-make
      script: cd $TRAVIS_BUILD_DIR/gnu-make-hello && make && ./hello
    - stage: gnatmake
      script: cd $TRAVIS_BUILD_DIR/gnatmake-hello && gnatmake hello.adb && ./hello
    - stage: ada-main-c-depend
      script: cd $TRAVIS_BUILD_DIR/ada-main-c-depend && make && gnatmake main.adb -largs i_am_c.o && ./main
    - stage: c-main-ada-depend
      script: cd $TRAVIS_BUILD_DIR/c-main-ada-depend && make && gnatmake -c i_am_ada.adb && gnatbind -n i_am_ada.ali && gnatlink i_am_ada.ali main.o -o main && ./main
    - stage: ada-main-cpp-depend
      script: cd $TRAVIS_BUILD_DIR/ada-main-cpp-depend && make && ./main
