language: c

before_install:
  - sudo apt-get install gnat

jobs:
  include:
    - stage: starter
      script: cd $TRAVIS_BUILD_DIR/gnu-make-hello && make
    - stage: starter
      script: cd $TRAVIS_BUILD_DIR/gnatmake-hello && gnatmake
